vcs:
  type: git
project:
  uuid: 8a4a7da6-a97c-4bb4-893a-b31664abfee4
  slug: spec-kitty
  node_id: d036a097a835
tools:
  available:
  - claude
  - opencode
  - codex
  selection:
    preferred_implementer: claude
    preferred_reviewer: codex
