"""Agent context management commands."""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

import typer
from rich.console import Console
from typing import Annotated

from specify_cli.core.paths import get_mission_dir, locate_project_root, require_explicit_mission
from specify_cli.core.mission_detection import detect_mission_directory
from specify_cli.core.execution_context import (
    ACTION_NAMES,
    ActionName,
    ActionContextError,
    resolve_action_context,
)

app = typer.Typer(name="context", help="Agent context management commands", no_args_is_help=True)

console = Console()


def _find_mission_directory(repo_root: Path, cwd: Path, explicit_mission: str | None = None) -> Path:
    """Find the mission directory from an explicit mission slug.

    Delegates to :func:`~specify_cli.core.mission_detection.detect_mission_directory`
    when possible, falling back to direct path resolution for backward compatibility.

    Args:
        repo_root: Repository root path
        cwd: Current working directory (unused — kept for signature compatibility)
        explicit_mission: Mission slug from --mission flag (required)

    Returns:
        Path to mission directory

    Raises:
        ValueError: If mission slug is not provided or directory doesn't exist
    """
    slug = require_explicit_mission(explicit_mission, command_hint="--mission <slug>")
    try:
        return detect_mission_directory(repo_root, explicit_mission=slug)
    except Exception:
        # Fallback: direct path resolution
        mission_dir = get_mission_dir(repo_root, slug)
        if not mission_dir.exists():
            raise ValueError(
                f"Mission directory not found: {mission_dir}. Check that '{slug}' is the correct mission slug."
            ) from None
        return mission_dir


@app.command(name="resolve")
def resolve_context(
    action: Annotated[
        str,
        typer.Option(
            "--action",
            help=(f"Action to resolve context for ({', '.join(ACTION_NAMES)})"),
        ),
    ],
    mission: Annotated[str | None, typer.Option("--mission", help="Mission slug (e.g., '020-my-mission')")] = None,
    feature: Annotated[str | None, typer.Option("--feature", hidden=True, help="[Deprecated] Use --mission")] = None,
    wp_id: Annotated[str | None, typer.Option("--wp-id", help="Work package ID (e.g., WP01)")] = None,
    base: Annotated[str | None, typer.Option("--base", help="Explicit base WP for implement")] = None,
    agent: Annotated[str | None, typer.Option("--agent", help="Agent name for exact command rendering")] = None,
    json_output: Annotated[bool, typer.Option("--json", help="Output results as JSON")] = False,
) -> None:
    """Resolve canonical mission/work-package/action context for prompt execution."""
    try:
        repo_root = locate_project_root()
        if repo_root is None:
            raise ActionContextError(
                "PROJECT_ROOT_UNRESOLVED",
                "Could not locate project root.",
            )

        if action not in ACTION_NAMES:
            raise ActionContextError(
                "INVALID_ACTION",
                f"Invalid action '{action}'. Expected one of: {', '.join(ACTION_NAMES)}.",
            )

        mission_slug = mission or feature
        context = resolve_action_context(
            repo_root,
            action=cast(ActionName, action),
            mission=mission_slug,
            wp_id=wp_id,
            base=base,
            agent=agent,
            cwd=Path.cwd(),
        )

        if json_output:
            print(json.dumps({"success": True, **context.to_dict()}, indent=2))
        else:
            console.print(f"[green]✓[/green] Resolved {action} context")
            console.print(f"  Mission: {context.mission_slug} ({context.detection_method})")
            console.print(f"  Target branch: {context.target_branch}")
            if context.wp_id:
                console.print(f"  Work package: {context.wp_id} ({context.lane})")
            if context.workspace_path:
                console.print(f"  Workspace: {context.workspace_path}")
            for name, command in context.commands.items():
                console.print(f"  {name}: {command}")
    except ActionContextError as exc:
        if json_output:
            print(json.dumps({"success": False, "error_code": exc.code, "error": str(exc)}, indent=2))
        else:
            console.print(f"[red]Error:[/red] {exc}")
        raise typer.Exit(1) from None


# update-context command removed — agent_context.py was deleted in WP10.
# Agent command files are now thin shims generated by shims/generator.py.
