"""Architectural ratchet — no-op-stable writes (umbrella #1914).

The #1914 ask: *"a 'run twice on an unchanged tree → git status clean'
architectural ratchet covering these surfaces."*

A *no-op-stable* surface is a governed/gate/tooling operation that re-renders a
tracked file on every run but MUST NOT dirty the working tree when nothing
substantive changed. Several surfaces achieve this today via four divergent
idioms (charter skip-write-modulo-volatile #1912, status.json byte-equal skip
#524, upgrade-metadata dirty-flag #1872, identity complete?-guard). Phase 1
(umbrella #1914) extracted a shared comparison core
(:func:`kernel.atomic.substantively_equal`) and adds this ratchet so a
regression that reintroduces an unconditional write fails CI.

Each surface is exercised inside a real git repo:

    1. run the op once  → commit the result (clean baseline),
    2. run the op again on the unchanged inputs,
    3. assert ``git status --porcelain`` is empty.

Step 3 is the strict assertion: if the second run rewrites the tracked file
(even with byte-identical-modulo-volatile content via ``os.replace``), git sees
a changed mtime/bytes and the tree goes dirty → the ratchet fails.

**Strictness proof (Phase 1 handoff):** a temporary rogue injection that drops
the charter ``_substantively_equal`` skip (forcing an unconditional
``guard.replace``) turned ``test_charter_synthesis_is_no_op_stable`` RED with::

    AssertionError: charter re-synthesis dirtied the tree (#1912/#1914):
      ' M .kittify/charter/provenance/directive-mission-type-scope-directive.yaml'
      ' M .kittify/charter/synthesis-manifest.yaml'

The injection was reverted; the guarded code keeps the ratchet GREEN.

**Phase-2 TODO (not yet covered — left for later phases, NOT flaked here):**

* charter DRG graph overlay ``.kittify/doctrine/graph.yaml`` (surface C-overlay)
  — the #1912 skip-write guard is wired for it, but the *regenerated* graph
  bytes are themselves non-deterministic across runs (~5% churn in a 20-run
  probe, from set/dict ordering in the graph emit), so a strict whole-tree
  assertion on it would FLAKE. The graph path is therefore excluded from the
  cleanliness assertion below (see ``_GRAPH_OVERLAY_RELPATH``). Closing this
  needs the graph emit made byte-deterministic first; tracked as a Phase-2 item.
* upgrade ``.kittify/metadata.yaml`` (#1872 dirty-flag) — needs a full upgrade
  runner harness; deterministic-in-CI setup is non-trivial.
* identity ``.kittify/config.yaml`` (#1916 complete?-guard / move-the-write) —
  blocked on #1916 (accept-gate risk; explicitly out of Phase-1 scope).
* doctrine pack-manifest ``fetched_at`` (surface M) — fires on pack-fetch, not a
  passive no-op read; borderline.

Add a surface here when (and only when) it can be driven deterministically in
CI — do not include a surface that would flake.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

pytestmark = [pytest.mark.architectural, pytest.mark.git_repo]

# The charter DRG graph overlay is guarded by the #1912 skip-write but its
# regenerated bytes are not byte-deterministic across runs (set/dict ordering in
# the graph emit), so it is excluded from the strict cleanliness assertion to
# avoid flaking. See the module docstring's Phase-2 TODO.
_GRAPH_OVERLAY_RELPATH = ".kittify/doctrine/graph.yaml"


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def _init_repo(repo: Path) -> None:
    repo.mkdir(parents=True, exist_ok=True)
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "ratchet@test.local")
    _git(repo, "config", "user.name", "ratchet")
    _git(repo, "config", "commit.gpgsign", "false")


def _commit_all(repo: Path, message: str) -> None:
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", message)


def _porcelain(repo: Path) -> str:
    return _git(repo, "status", "--porcelain")


def _porcelain_lines(repo: Path, *, exclude: tuple[str, ...] = ()) -> list[str]:
    """Porcelain status lines, dropping any whose path matches *exclude*."""
    lines: list[str] = []
    for line in _porcelain(repo).splitlines():
        # Porcelain line shape: ``XY <path>`` (status code, space, path).
        path = line[3:] if len(line) > 3 else line
        if path in exclude:
            continue
        lines.append(line)
    return lines


# ---------------------------------------------------------------------------
# Surface A/B/C — charter synthesis (provenance, manifest, body, graph overlay)
# Guard: #1912 skip-write-modulo-volatile, now via the shared comparison core.
# ---------------------------------------------------------------------------


def _synthesize_unchanged_pack(repo_root: Path, run_id: str) -> None:
    """Synthesize the minimal fixture pack into ``repo_root`` with ``run_id``.

    Every governed run carries a fresh ``run_id`` (as every real invocation
    does) but identical semantic inputs — exactly the no-op case #1912 guards.
    """
    from charter.synthesizer import (
        FixtureAdapter,
        SynthesisRequest,
        SynthesisTarget,
        synthesize,
    )

    fixture_root = (
        Path(__file__).resolve().parent.parent
        / "charter"
        / "fixtures"
        / "synthesizer"
    )
    target = SynthesisTarget(
        kind="directive",
        slug="mission-type-scope-directive",
        title="Mission Type Scope Directive",
        artifact_id="PROJECT_001",
        source_section="mission_type",
    )
    request = SynthesisRequest(
        target=target,
        interview_snapshot={
            "mission_type": "software_dev",
            "language_scope": ["python"],
            "testing_philosophy": "test-driven development with high coverage",
            "neutrality_posture": "balanced",
            "selected_directives": ["DIRECTIVE_003"],
            "risk_appetite": "moderate",
        },
        doctrine_snapshot={
            "directives": {
                "DIRECTIVE_003": {
                    "id": "DIRECTIVE_003",
                    "title": "Decision Documentation",
                    "body": "Document significant architectural decisions via ADRs.",
                }
            },
            "tactics": {},
            "styleguides": {},
        },
        drg_snapshot={
            "nodes": [
                {
                    "urn": "directive:DIRECTIVE_003",
                    "kind": "directive",
                    "id": "DIRECTIVE_003",
                }
            ],
            "edges": [],
            "schema_version": "1",
        },
        run_id=run_id,
        adapter_hints={"language": "python"},
    )
    synthesize(request, adapter=FixtureAdapter(fixture_root=fixture_root), repo_root=repo_root)


def test_charter_synthesis_is_no_op_stable(tmp_path: Path) -> None:
    """Re-synthesizing an unchanged pack with a fresh run_id → tree stays clean.

    Covers surfaces A (provenance), B (manifest), C (body + graph overlay).
    The second run carries a different ``run_id`` (volatile) but identical
    inputs; the shared no-op-stability comparison must skip every write.
    """
    repo = tmp_path / "repo"
    _init_repo(repo)

    _synthesize_unchanged_pack(repo, run_id="01AAAAAAAAAAAAAAAAAAAAAAAA")
    _commit_all(repo, "baseline charter synthesis")
    # Baseline must be clean modulo the non-deterministic graph overlay.
    assert _porcelain_lines(repo, exclude=(_GRAPH_OVERLAY_RELPATH,)) == [], (
        "baseline commit left the tree dirty"
    )

    # Second governed run — fresh run_id, identical inputs (the #1912 no-op).
    _synthesize_unchanged_pack(repo, run_id="01BBBBBBBBBBBBBBBBBBBBBBBB")

    dirty = _porcelain_lines(repo, exclude=(_GRAPH_OVERLAY_RELPATH,))
    assert dirty == [], (
        "charter re-synthesis dirtied the tree (#1912/#1914): "
        f"{dirty!r}. A no-op run must skip every write so the committed "
        "bytes/timestamps survive. (The graph overlay is excluded as a "
        "documented Phase-2 non-determinism TODO.)"
    )


# ---------------------------------------------------------------------------
# Surface D — status.json materialize. Guard: #524 byte-equal skip-write.
# ---------------------------------------------------------------------------


def _materialize_status(feature_dir: Path) -> None:
    """Append one deterministic event and materialize status.json.

    The event timestamp is fixed, so the reduced snapshot is byte-stable across
    runs — a second materialize on the same event log must skip the write.
    """
    from specify_cli.status.models import Lane, StatusEvent
    from specify_cli.status.reducer import materialize
    from specify_cli.status.store import append_event, read_events

    feature_dir.mkdir(parents=True, exist_ok=True)
    meta_path = feature_dir / "meta.json"
    if not meta_path.exists():
        meta_path.write_text(
            json.dumps(
                {
                    "created_at": "2026-04-01T10:00:00+00:00",
                    "friendly_name": feature_dir.name,
                    "mission_id": "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                    "mission_number": 34,
                    "mission_slug": feature_dir.name,
                    "mission_type": "software-dev",
                    "slug": feature_dir.name,
                    "target_branch": "main",
                },
                indent=2,
                ensure_ascii=False,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
    # Append the event only once (the event log is the genuine input; surface K
    # is append-only and out of the no-op class). Re-materializing the SAME log
    # is the no-op we ratchet.
    if not read_events(feature_dir):
        append_event(
            feature_dir,
            StatusEvent(
                event_id="01TESTNOOPSTABLE0000000001",
                mission_slug=feature_dir.name,
                wp_id="WP01",
                from_lane=Lane("planned"),
                to_lane=Lane("in_progress"),
                at="2026-04-21T12:00:00+00:00",
                actor="ratchet",
                force=False,
                execution_mode="worktree",
                mission_id="01ARZ3NDEKTSV4RRFFQ69G5FAV",
            ),
        )
    materialize(feature_dir)


def test_status_json_materialize_is_no_op_stable(tmp_path: Path) -> None:
    """Re-materializing the same event log → status.json is not rewritten.

    Covers surface D (#524). The reduced snapshot carries no volatile fields, so
    a byte-equal skip keeps the tracked status.json untouched on the second run.
    """
    repo = tmp_path / "repo"
    _init_repo(repo)
    feature_dir = repo / "kitty-specs" / "034-no-op-stable"

    _materialize_status(feature_dir)
    _commit_all(repo, "baseline status materialize")
    assert _porcelain(repo) == "", "baseline commit left the tree dirty"

    # Second materialize on the unchanged event log — must skip the write.
    _materialize_status(feature_dir)

    dirty = _porcelain(repo)
    assert dirty == "", (
        "status.json re-materialize dirtied the tree (#524/#1914): "
        f"{dirty.splitlines()!r}. A byte-identical snapshot must skip the write."
    )
